#ifndef PIN_DEF_H
#define PIN_DEF_H

/* Definitions for peripheral AXI_GPIO_ADDRESS */
#define  AXI_GPIO_ADDRESS_BASEADDR 0x41200000
#define  AXI_GPIO_ADDRESS_HIGHADDR 0x4120FFFF


/* Definitions for peripheral AXI_GPIO_READREADY */
#define  AXI_GPIO_READREADY_BASEADDR 0x41210000
#define  AXI_GPIO_READREADY_HIGHADDR 0x4121FFFF


/* Definitions for peripheral AXI_GPIO_READVALID */
#define  AXI_GPIO_READVALID_BASEADDR 0x41220000
#define  AXI_GPIO_READVALID_HIGHADDR 0x4122FFFF


/* Definitions for peripheral AXI_GPIO_READVALUE_H */
#define  AXI_GPIO_READVALUE_H_BASEADDR 0x41230000
#define  AXI_GPIO_READVALUE_H_HIGHADDR 0x4123FFFF


/* Definitions for peripheral AXI_GPIO_READVALUE_L */
#define  AXI_GPIO_READVALUE_L_BASEADDR 0x41240000
#define  AXI_GPIO_READVALUE_L_HIGHADDR 0x4124FFFF


/* Definitions for peripheral AXI_GPIO_WRITEREADY */
#define  AXI_GPIO_WRITEREADY_BASEADDR 0x41250000
#define  AXI_GPIO_WRITEREADY_HIGHADDR 0x4125FFFF


/* Definitions for peripheral AXI_GPIO_WRITEVALID */
#define  AXI_GPIO_WRITEVALID_BASEADDR 0x41260000
#define  AXI_GPIO_WRITEVALID_HIGHADDR 0x4126FFFF


/* Definitions for peripheral AXI_GPIO_WRITEVALUE_H */
#define  AXI_GPIO_WRITEVALUE_H_BASEADDR 0x41270000
#define  AXI_GPIO_WRITEVALUE_H_HIGHADDR 0x4127FFFF

/* Definitions for peripheral AXI_GPIO_WRITEVALUE_L */
#define  AXI_GPIO_WRITEVALUE_L_BASEADDR 0x41280000
#define  AXI_GPIO_WRITEVALUE_L_HIGHADDR 0x4128FFFF

#endif